<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pas_dual_arm_bringup</name>
  <version>0.0.0</version>
  <description>Bringup package for the PAS Dual Arm robot</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>dual_arm_torso</exec_depend>
  <exec_depend>omni_base_description</exec_depend>
  <exec_depend>pal_urdf_utils</exec_depend>
  <exec_depend>kortex_description</exec_depend>
  <exec_depend>pan_tilt_description</exec_depend>
  <exec_depend>realsense2_description</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
